### ISSUE TITLE
Portal 2: no sound

### ISSUE THREAD

**Issue by colinmarc** [colinmarc/magic-mirror#27]
```
thread 'pulse server (/tmp/mm.f3cm7EYE3OWtLhEm/pulse/native)' panicked at src/compositor/audio/pulse.rs:389:21:
assertion `left == right` failed
  left: 44100
 right: 48000
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::panicking::assert_failed_inner
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:410:17
   3: core::panicking::assert_failed
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:365:5
   4: mmserver::compositor::audio::pulse::PulseServer::clock_tick
             at ./src/compositor/audio/pulse.rs:389:21
   5: mmserver::compositor::audio::pulse::PulseServer::run
             at ./src/compositor/audio/pulse.rs:236:25
   6: mmserver::compositor::audio::EncodePipeline::new::{{closure}}
             at ./src/compositor/audio.rs:74:28
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace
```

**Comment by colinmarc** [comment]
Same assertion on Northgard.
